[package]
name = "kvim-editor"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
# kvim crates
kvim-core.workspace = true
kvim-input.workspace = true
kvim-settings.workspace = true

# Basics
thiserror.workspace = true

# Text case mapping
icu_casemap.workspace = true

# Text segmentation
unicode-segmentation.workspace = true
