[package]
name = "kvim"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "kvim"
path = "src/main.rs"

[dependencies]
# kvim crates
kvim-embed = { workspace = true, features = ["worktree", "all-grammars"] }
kvim-path.workspace = true
kvim-settings.workspace = true
kvim-terminal.workspace = true

# Basics
thiserror.workspace = true

# Terminal
ratatui = { workspace = true, features = ["crossterm"] }

# Runtime
tokio.workspace = true
