[package]
name = "kvim"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "kvim"
path = "src/main.rs"

[dependencies]
# kvim crates
kvim-language.workspace = true
kvim-settings.workspace = true
kvim-tui.workspace = true

# Basics
thiserror.workspace = true

# Runtime
tokio.workspace = true
