[package]
name = "kvim"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "kvim"
path = "src/main.rs"

[dependencies]
# kvim crates
kvim-language = { workspace = true, features = ["all-grammars"] }
kvim-path.workspace = true
kvim-runtime.workspace = true
kvim-settings.workspace = true
kvim-terminal.workspace = true
kvim-tui = { workspace = true, features = ["all-grammars"] }

# Basics
thiserror.workspace = true

# Terminal
ratatui.workspace = true

# Runtime
tokio.workspace = true
