[package]
name = "kvim-runtime"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
# kvim crates
kvim-path.workspace = true

# Basics
thiserror.workspace = true

# Runtime
notify.workspace = true
tokio.workspace = true
tokio-util.workspace = true
