[package]
name = "kvim-terminal"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
# kvim crates
kvim-keymap.workspace = true

# Basics
thiserror.workspace = true

# Terminal
crossterm.workspace = true
futures-util.workspace = true

# Runtime
tokio.workspace = true
