[package]
name = "kvim-lsp"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
# kvim crates
kvim-path.workspace = true

# Basics
thiserror.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true

# Runtime
tokio.workspace = true
